import { NewsContentTagModel } from './NewsContentTagModel'

export interface StoryModel {
    id: string
    internalID: string
    title: string
    summary: string
    autoGeneratedSummary: string
    abstract: string[]
    published: number
    updatedAt: number
    wordCount: number
    premium: false
    secondaryBrands: string[]
    byline: string
    shortURL: string
    longURL: string
    primaryCategory: string
    primarySite: string
    eyebrowSite: string
    image: string
    thumbnailImage: string
    card: string
    contentTags: NewsContentTagModel[]
}
